from flask import Flask
from flask import render_template
from flask_mail import Mail, Message
from flask import request



# configuration

MAIL_SERVER='smtp.gmail.com'
MAIL_PORT=465
MAIL_USE_TLS = False
MAIL_USE_SSL= True
MAIL_USERNAME = 'visamailman@gmail.com'
MAIL_PASSWORD = 'phoisthebest'

app = Flask(__name__)
app.config.from_object(__name__)
mail = Mail(app)

@app.route('/mlist', methods = ['POST'])
def mlist():
	try:
		name = request.form['name']
		email = request.form['email']
		msg = Message(sender=email,
	                  recipients=['mimi.pham@yale.edu'],
	                  subject='Add Me to the ViSA Mailing List',
	                  html='Please add me to the visa mailing list.<br>email: '+email+'<br>name: '+name+
	                  '<br><br>' + '<em>Generated by the ViSA website<em>')
		mail.send(msg)
	except:
		return "fail"
	else:
		return "success"

@app.route('/')
def index():
	return render_template('index.html')




if __name__ == '__main__':
	app.run(debug=True)
