from flask import Flask
from flask import render_template
from flask_mail import Mail, Message
from flask import request
from os import listdir
from os.path import isfile, join
import random
import os



# configuration

MAIL_SERVER='smtp.gmail.com'
MAIL_PORT=465
MAIL_USE_TLS = False
MAIL_USE_SSL= True
MAIL_USERNAME = os.environ["VISA_MAIL_USERNAME"]
MAIL_PASSWORD = os.environ["VISA_MAIL_PASSWORD"]
MAIL_RECIPIENT = os.environ["VISA_MAIL_SECRETARY"]

app = Flask(__name__)
app.config.from_object(__name__)
mail = Mail(app)

@app.route('/mlist', methods = ['POST'])
def mlist():
	try:
		name = request.form['name']
		email = request.form['email']
		msg = Message(sender=email,
	                  recipients=[MAIL_RECIPIENT],
	                  subject='Add Me to the ViSA Mailing List',
	                  html='Please add me to the visa mailing list.<br>email: '+email+'<br>name: '+name+
	                  '<br><br>' + '<em>Generated by the ViSA website<em>')
		mail.send(msg)
	except:
		return "fail"
	else:
		return "success"

@app.route('/')
def index():
	mypath = 'static/img/events'
	files = [ join(mypath,f) for f in listdir(mypath) if isfile(join(mypath,f)) ]
	random.shuffle(files)
	return render_template('index.html', files=files)




if __name__ == '__main__':
	app.run()
